services:
  - type: web
    name: acme-backend
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: RECAPTCHA_SECRET_KEY
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_NAME_OPORTUNIDADES
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        value: "5432"
